# Generated by Django 4.2.13 on 2026-05-19 07:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (EN)')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#1ab69d', max_length=20, verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (EN)')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('short_description_uz', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZ)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (RU)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Qisqa tavsif (EN)')),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Matn (UZ)')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Matn (RU)')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Matn (EN)')),
                ('image', models.ImageField(upload_to='news/%Y/%m/', verbose_name='Rasm')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilingan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
