# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Dastur nomi')),
                ('program_type', models.CharField(choices=[('erasmus', 'Erasmus+'), ('daad', 'DAAD'), ('fulbright', 'Fulbright'), ('other', 'Boshqa')], default='other', max_length=30, verbose_name='Tur')),
                ('duration_months', models.PositiveIntegerField(default=6, verbose_name='Muddati (oy)')),
                ('funding', models.CharField(blank=True, max_length=200, verbose_name='Moliyalashtirish')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Ariza oxirgi muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('url', models.URLField(blank=True, verbose_name='Batafsil URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.country', verbose_name='Davlat')),
                ('host_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partner', verbose_name='Qabul qiluvchi universitet')),
            ],
            options={
                'verbose_name': 'Mobillik dasturi',
                'verbose_name_plural': 'Mobillik dasturlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobilityStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('direction', models.CharField(choices=[('outgoing', 'Chiquvchi'), ('incoming', 'Kiruvchi')], max_length=20, verbose_name="Yo'nalish")),
                ('faculty', models.CharField(max_length=200, verbose_name='Fakultet')),
                ('academic_year', models.CharField(max_length=20, verbose_name="O'quv yili")),
                ('semester', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Semestr')),
                ('home_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_students', to='partnerships.country', verbose_name='Vatani')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='mobility.mobilityprogram', verbose_name='Dastur')),
            ],
            options={
                'verbose_name': 'Mobillik talabasi',
                'verbose_name_plural': 'Mobillik talabalari',
                'ordering': ['-academic_year'],
            },
        ),
    ]
