# Generated by Django 6.0.6 on 2026-07-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilityprogram',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='mobilityprogram',
            name='duration',
            field=models.CharField(default='6 oy', max_length=50, verbose_name='Muddati'),
        ),
    ]
