# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCountryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Talabalar soni')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20, verbose_name="O'quv yili")),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_stat', to='partnerships.country', verbose_name='Davlat')),
            ],
            options={
                'verbose_name': "Davlat bo'yicha talabalar",
                'verbose_name_plural': "Davlatlar bo'yicha talabalar",
            },
        ),
        migrations.CreateModel(
            name='InternationalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD'), ('exchange', 'Almashinuv')], max_length=20, verbose_name='Daraja')),
                ('faculty', models.CharField(max_length=200, verbose_name='Fakultet')),
                ('admission_year', models.PositiveIntegerField(verbose_name='Qabul yili')),
                ('status', models.CharField(choices=[('studying', "O'qimoqda"), ('graduated', 'Bitirgan'), ('exchange_out', 'Xorijda')], default='studying', max_length=20, verbose_name='Holati')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Rasm')),
                ('testimonial_uz', models.TextField(blank=True, verbose_name='Fikr (UZ)')),
                ('testimonial_en', models.TextField(blank=True, verbose_name='Fikr (EN)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='partnerships.country', verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Xalqaro talaba',
                'verbose_name_plural': 'Xalqaro talabalar',
                'ordering': ['-admission_year', 'last_name'],
            },
        ),
    ]
