# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Agentlik nomi')),
                ('short_name', models.CharField(max_length=20, verbose_name='Qisqa nomi')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='rankings/logos/', verbose_name='Logo')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
            ],
            options={
                'verbose_name': 'Reyting agentligi',
                'verbose_name_plural': 'Reyting agentliklari',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_name', models.CharField(max_length=300, verbose_name='Reyting nomi')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('position', models.CharField(max_length=100, verbose_name="O'rin")),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Ball')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Kategoriya')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='rankings/certs/', verbose_name='Sertifikat')),
                ('details_url', models.URLField(blank=True, verbose_name='Batafsil URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='rankings.rankingagency', verbose_name='Agentlik')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinglar',
                'ordering': ['-year', 'agency'],
            },
        ),
    ]
