# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (EN)')),
                ('subtitle_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('subtitle_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Rasm')),
                ('btn_text_uz', models.CharField(default='Batafsil', max_length=100, verbose_name='Tugma matni (UZ)')),
                ('btn_url', models.CharField(default='#', max_length=200, verbose_name='Tugma URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hero slayd',
                'verbose_name_plural': 'Hero slaydlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (EN)')),
                ('description_uz', models.CharField(blank=True, max_length=200, verbose_name='Tavsif (UZ)')),
                ('icon_class', models.CharField(default='ri-global-line', max_length=100, verbose_name='Icon class (remixicon)')),
                ('url', models.URLField(verbose_name='URL')),
                ('color', models.CharField(default='#1ab69d', max_length=20, verbose_name='Rang (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Tez havola',
                'verbose_name_plural': 'Tez havolalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name_uz', models.CharField(default="Xalqaro Aloqalar Bo'limi", max_length=200, verbose_name="Bo'lim nomi (UZ)")),
                ('office_name_ru', models.CharField(default='Международный отдел', max_length=200, verbose_name="Bo'lim nomi (RU)")),
                ('office_name_en', models.CharField(default='International Office', max_length=200, verbose_name="Bo'lim nomi (EN)")),
                ('slogan_uz', models.CharField(default='Global Aloqalar, Mahalliy Muvaffaqiyat', max_length=300, verbose_name='Slogan (UZ)')),
                ('slogan_ru', models.CharField(blank=True, max_length=300, verbose_name='Slogan (RU)')),
                ('slogan_en', models.CharField(blank=True, max_length=300, verbose_name='Slogan (EN)')),
                ('email', models.EmailField(default='international@namdu.uz', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+998 69 210-01-35', max_length=50, verbose_name='Telefon')),
                ('address_uz', models.CharField(default="Namangan sh., Boburshox ko'chasi, 161-uy", max_length=300, verbose_name='Manzil (UZ)')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (RU)')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (EN)')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('namdu_main_url', models.URLField(default='https://namdu.uz', verbose_name='NamDU asosiy sayt')),
                ('meta_keywords', models.TextField(blank=True, verbose_name="Meta kalit so'zlar")),
                ('meta_description_uz', models.TextField(blank=True, verbose_name='Meta tavsif (UZ)')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_universities', models.PositiveIntegerField(default=47, verbose_name='Hamkor universitetlar')),
                ('partner_countries', models.PositiveIntegerField(default=28, verbose_name='Hamkor davlatlar')),
                ('exchange_students', models.PositiveIntegerField(default=312, verbose_name='Almashinuv talabalari')),
                ('scopus_articles', models.PositiveIntegerField(default=189, verbose_name='Scopus maqolalar')),
                ('active_grants', models.PositiveIntegerField(default=32, verbose_name='Aktiv grantlar')),
                ('visiting_professors', models.PositiveIntegerField(default=24, verbose_name='Mehmon professorlar')),
                ('mou_agreements', models.PositiveIntegerField(default=63, verbose_name='MOU shartnomalari')),
                ('conferences_held', models.PositiveIntegerField(default=18, verbose_name="O'tkazilgan konferensiyalar")),
            ],
            options={
                'verbose_name': 'Statistika raqamlar',
                'verbose_name_plural': 'Statistika raqamlar',
            },
        ),
    ]
