# Generated by Django 4.2.13 on 2026-05-19 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Hero slayd', 'verbose_name_plural': 'Hero slaydlar'},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='auto_play_duration',
            field=models.PositiveIntegerField(default=5, verbose_name="Ko'rsatish vaqti (soniya)"),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='btn2_text_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tugma 2 matni (UZ)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='btn2_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tugma 2 URL'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroslide',
            name='media_type',
            field=models.CharField(choices=[('image', 'Rasm'), ('gif', 'GIF animatsiya'), ('video', 'Video (MP4)')], default='image', max_length=10, verbose_name='Media turi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='overlay_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Qoplama rangi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='overlay_opacity',
            field=models.FloatField(default=0.5, help_text="0 = shaffof, 1 = to'liq qora", verbose_name='Qoplaма qoralik (0-1)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 formatdagi video yuklang (max 50MB)', null=True, upload_to='hero/videos/', verbose_name='Video (MP4)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video_poster',
            field=models.ImageField(blank=True, help_text="Video yuklanayotganda ko'rsatiladigan rasm", null=True, upload_to='hero/posters/', verbose_name='Video muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='btn_text_uz',
            field=models.CharField(default='Batafsil', max_length=100, verbose_name='Tugma 1 matni (UZ)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='btn_url',
            field=models.CharField(default='#', max_length=200, verbose_name='Tugma 1 URL'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Rasm yoki GIF fayl yuklang (.jpg, .png, .gif)', null=True, upload_to='hero/', verbose_name='Rasm / GIF'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="0 = birinchi ko'rsatiladi", verbose_name='Tartib raqami'),
        ),
    ]
