# Generated by Django 4.2.13 on 2026-05-19 07:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Nomi (EN)')),
                ('slug', models.SlugField(blank=True, max_length=450, unique=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Tavsif (EN)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='conferences/', verbose_name='Muqova rasmi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('location_uz', models.CharField(blank=True, max_length=300, verbose_name='Manzil (UZ)')),
                ('format', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Gibrid')], default='offline', max_length=20, verbose_name='Format')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Ishtirokchilar soni')),
                ('countries_count', models.PositiveIntegerField(default=0, verbose_name='Davlatlar soni')),
                ('registration_url', models.URLField(blank=True, verbose_name="Ro'yxatdan o'tish URL")),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Ariza muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Konferensiya',
                'verbose_name_plural': 'Konferensiyalar',
                'ordering': ['-start_date'],
            },
        ),
    ]
