# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Unvon')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professors/photos/', verbose_name='Rasm')),
                ('specialization_uz', models.CharField(blank=True, max_length=300, verbose_name='Mutaxassisligi (UZ)')),
                ('specialization_en', models.CharField(blank=True, max_length=300, verbose_name='Mutaxassisligi (EN)')),
                ('bio_uz', models.TextField(blank=True, verbose_name='Tarjimai hol (UZ)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Tarjimai hol (EN)')),
                ('visit_start', models.DateField(blank=True, null=True, verbose_name='Tashrif boshlanishi')),
                ('visit_end', models.DateField(blank=True, null=True, verbose_name='Tashrif tugashi')),
                ('lecture_topic_uz', models.CharField(blank=True, max_length=400, verbose_name="Ma'ruza mavzusi (UZ)")),
                ('status', models.CharField(choices=[('current', 'Hozirgi'), ('past', "O'tgan"), ('upcoming', 'Kelasi')], default='current', max_length=20, verbose_name='Holati')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.country', verbose_name='Davlat')),
                ('home_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.partner', verbose_name='Asosiy universitet')),
            ],
            options={
                'verbose_name': 'Mehmon professor',
                'verbose_name_plural': 'Mehmon professorlar',
                'ordering': ['-visit_start'],
            },
        ),
    ]
