# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('co2', 'CO₂ qisqarish'), ('trees', 'Daraxtlar'), ('recycling', 'Qayta ishlash'), ('energy', 'Energiya tejash'), ('water', 'Suv tejash'), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya')),
                ('value', models.CharField(max_length=50, verbose_name='Qiymat')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Birlik')),
                ('description_uz', models.CharField(blank=True, max_length=200, verbose_name='Tavsif (UZ)')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Yil')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Ikonka')),
            ],
            options={
                'verbose_name': "Green ko'rsatkich",
                'verbose_name_plural': "Green ko'rsatkichlar",
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SDGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='SDG raqami')),
                ('name_uz', models.CharField(max_length=300, verbose_name='Nomi (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('color', models.CharField(default='#1ab69d', max_length=20, verbose_name='Rang')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='sdg/icons/', verbose_name='SDG ikonkasi')),
                ('namdu_activities_uz', models.TextField(blank=True, verbose_name='NamDU faoliyati (UZ)')),
                ('namdu_activities_en', models.TextField(blank=True, verbose_name='NamDU faoliyati (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'SDG Maqsad',
                'verbose_name_plural': 'SDG Maqsadlar',
                'ordering': ['number'],
            },
        ),
    ]
