# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Davlat nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Davlat nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Davlat nomi (EN)')),
                ('code', models.CharField(max_length=2, verbose_name='Kod (ISO 3166-1 alpha-2)')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Bayroq')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi')),
                ('partner_type', models.CharField(choices=[('university', 'Universitet'), ('research', 'Ilmiy markaz'), ('government', 'Davlat tashkiloti'), ('ngo', 'NNT'), ('other', 'Boshqa')], default='university', max_length=20, verbose_name='Tur')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('partnership_since', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hamkorlik boshlanishi (yil)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partnerships.country', verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Shartnoma nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Shartnoma nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Shartnoma nomi (EN)')),
                ('signed_date', models.DateField(verbose_name='Imzolangan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', "Muddati o'tgan"), ('pending', 'Kutilmoqda')], default='active', max_length=20, verbose_name='Holati')),
                ('document', models.FileField(blank=True, null=True, upload_to='mou/docs/', verbose_name='Hujjat (PDF)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mous', to='partnerships.partner', verbose_name='Hamkor')),
            ],
            options={
                'verbose_name': 'MOU shartnoma',
                'verbose_name_plural': 'MOU shartnomalar',
                'ordering': ['-signed_date'],
            },
        ),
    ]
