# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Nomi (EN)')),
                ('report_type', models.CharField(choices=[('annual', 'Yillik hisobot'), ('sustainability', 'Barqarorlik'), ('research', 'Ilmiy faoliyat'), ('mobility', 'Akademik mobillik'), ('policy', 'Siyosat hujjati'), ('other', 'Boshqa')], default='annual', max_length=30, verbose_name='Tur')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reports/covers/', verbose_name='Muqova')),
                ('file_uz', models.FileField(blank=True, null=True, upload_to='reports/files/', verbose_name='Fayl (UZ)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='reports/files/', verbose_name='Fayl (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sahifalar soni')),
                ('is_public', models.BooleanField(default=True, verbose_name='Ommaviy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-year', 'report_type'],
            },
        ),
    ]
