# Generated by Django 4.2.13 on 2026-05-19 07:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Nomi (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Nomi (EN)')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Tavsif (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/', verbose_name='Rasm')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanishi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugashi')),
                ('beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Foydalanuvchilar soni')),
                ('location_uz', models.CharField(blank=True, max_length=300, verbose_name='Joylashuv')),
                ('sdg_connection', models.CharField(blank=True, max_length=100, verbose_name="SDG bog'lanishi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jamoaviy loyiha',
                'verbose_name_plural': 'Jamoaviy loyihalar',
                'ordering': ['-start_date'],
            },
        ),
    ]
