# Generated by Django 4.2.13 on 2026-05-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Soha (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Soha (EN)')),
            ],
            options={
                'verbose_name': 'Ilmiy soha',
                'verbose_name_plural': 'Ilmiy sohalar',
            },
        ),
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Grant nomi (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Grant nomi (EN)')),
                ('funder', models.CharField(max_length=300, verbose_name='Moliyalovchi tashkilot')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miqdor (USD)')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('pending', 'Kutilmoqda')], default='active', max_length=20, verbose_name='Holati')),
                ('principal_investigator', models.CharField(max_length=200, verbose_name='Asosiy tadqiqotchi')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grantlar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Maqola nomi')),
                ('authors', models.CharField(max_length=500, verbose_name='Mualliflar')),
                ('journal', models.CharField(max_length=300, verbose_name='Jurnal')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('quartile', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('OA', 'Open Access')], max_length=5, verbose_name='Kvartil')),
                ('database', models.CharField(choices=[('scopus', 'Scopus'), ('wos', 'Web of Science'), ('google_scholar', 'Google Scholar'), ('other', 'Boshqa')], default='scopus', max_length=30, verbose_name='Baza')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('citations', models.PositiveIntegerField(default=0, verbose_name='Iqtiboslar soni')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sahifada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.researcharea', verbose_name='Ilmiy soha')),
            ],
            options={
                'verbose_name': 'Nashr',
                'verbose_name_plural': 'Nashrlar',
                'ordering': ['-year', '-citations'],
            },
        ),
    ]
